[HAL]

# The run script first uses halcmd to execute any HALFILE
# files, and then to execute any individual HALCMD commands.

# list of hal config files to run through halcmd
# files are executed in the order in which they appear

HALFILE =		CRAMPS.hal

# list of halcmd commands to execute
# commands are executed in the order in which they appear
#HALCMD = save neta

POSTGUI_HALFILE = 3D.postgui.hal
